spring:
  profiles:
    active: local # 기본 환경 선택

env:
  servers:
    dev1.example.com,dev2.example.com,dev3.example.com



my:
  email: nicekkong@gmail.com


number: 100

app:
  jwtSecret: TORINGTOKEN123
  jwtExpirationInMs: 10800000 # 1000 * 60 * 60 * 3 = 3Days

# 인증이 필요 없는 URL
permitAllUrls:
  /api/login/**,
  /api/signup/**,
  /api/memberInfo,
  /api/mentoring/**,
  /file/**,
  /api/decision/main,
  /mask/**

# aws 설정
cloud:
  aws:
    credentials:
      accessKey: AKIAJUFPOBHXMCTZKEPQ
      secretKey: 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
    s3:
      bucket: toringfile
    region:
      static: ap-northeast-2
    stack:
      auto: false
