spring:
  profiles:
    active: local # 기본 환경 선택

env:
  servers:
    dev1.example.com,dev2.example.com,dev3.example.com



my:
  email: nicekkong@gmail.com


number: 100

app:
  jwtSecret: TORINGTOKEN123
  jwtExpirationInMs: 10800000 # 1000 * 60 * 60 * 3